#!/bin/bash

## written by theadamcraig
## updated 3/26/2021
## Re-worked the account creation section of the script. The jamf policy no longer needs to create the account
## variables changed. eliminated variable 7, old password is not necessary


##Based on script found at FOUND AT https://github.com/therealmacjeezy/Scripts/blob/master/LAPS%20for%20Mac/LAPSforMac.sh

########### Parameters (Required) ###############
# 4 - API Username String
# 5 - API Password String
# 6 - Rescue Admin Username
# 7 - Local Admin Username
# 8 - Local Admin Password

passLocation="/Library/Application Support/YourCompany/rescue"
#get the filepath
pathLocation=$(dirname "$passLocation")
#make sure the filepath exists
mkdir -p "$pathLocation"
# locate the pythonscript
pythonScript="$pathLocation/passphrase/pass_phrase.py"
# check to see if python is installed. pass_phrase.py should work with python 2 or 3
pythonCheck=$(python -V  2>&1)

## if the passphrase PythonScript doesn't exist then install it
if [[ ! -e "$pythonScript" ]] ; then
	jamf policy -trigger installpassphrase
fi
sleep 5

# HARDCODED VALUES
jssURL="https://covermymeds.jamfcloud.com"
udid=$(/usr/sbin/system_profiler SPHardwareDataType | /usr/bin/awk '/Hardware UUID:/ { print $3 }')
## extAttName also needs to be changed in the curl command in setEAStatus function.
extAttName="\"RescuePassword\""

## If the passphrase script exists get the passphrase from there. Else do a random passphrase
if [[ -e "$pythonScript" ]]  && [[ "$pythonCheck" == *"Python"* ]]; then
	cd "$pathLocation/passphrase"
	echo "Python Script installed. Python check passed == $pythonCheck"
	newPass=$(python "$pythonScript" -s "" --min=4 --max=5 -L)
	echo "$newPass" > "$passLocation"
	getPass=$(cat "$passLocation")	
else
	echo "Python script missing, or python check failed == $pythonCheck"
	newPass=$(env LC_CTYPE=C tr -dc "A-HJ-KM-Za-hj-km-z0-9" < /dev/urandom | head -c 24 > "$passLocation")
	getPass=$(cat "$passLocation")
fi

# Decrypt String
DecryptString() {
	# Usage: ~$ DecryptString "Encrypted String" "Salt" "Passphrase"
	echo "${1}" | /usr/bin/openssl enc -aes256 -d -a -A -S "${2}" -k "${3}"
}

#####################################################
## VERIFY WE HAVE ALL THE VARIABLES THAT WE NEED
#####################################################

# Account Information
if [[ -z "$4" ]]; then 
    echo "Error: API USER MISSING"
    exit 1
else
	apiUser="$4"        
fi

if [[ -z "$5" ]]; then
	echo "Error: API PASS MISSING"
    exit 1        
else
	apiPass="$5"
fi

if [[ -z "$6" ]]; then
    echo "ERROR: RESCUE USERNAME NAME MISSING"
    exit 1
else
    rescueUser="$6"
fi

if [[ -z "$8" ]];then
	echo "ERROR: LOCAL ADMIN USERNAME MISSING"
	exit 1
else
	adminName="$8"
fi
if [[ -z "$9" ]];then
	echo "ERROR: LOCAL ADMIN PASSWORD MISSING"
	exit 1
else
	adminPass="$9"
fi

#####################################################
#####################################################
## Functions that the script will use
#####################################################
#####################################################


userExists(){
	local userToCheck="$1"
	# returns True if the user exists false if the user does not
	local userCheck
	userCheck=$(dscl . list /Users | grep "$userToCheck" | grep -v "_mbsetupuser" )
	if [[ "$userCheck" == "$userToCheck" ]] ; then
		local exists="true"
	else
		local exists="false"
	fi
	echo "$exists"
}

passwordCorrect() {
	#returns true if the user password is correct false if it is not
	local userName="${1}"
	local passWord="${2}"
	local passCheck
	passCheck=$(/usr/bin/dscl /Local/Default -authonly "$userName" "$passWord")
	if [[ -z "$passCheck" ]]; then
		local correct="true"
	else
		local correct="false"
	fi
	echo "$correct"
}

fileVaultUserAccess() {
	# returns true if the user has filevault access. false if they do not
	local userToCheck="$1"
	if [[ $(fdesetup list | grep "$userToCheck") == *"$userToCheck"* ]] ; then
		local fvAccess="true"
	else
		local fvAccess="false"
	fi
	echo "$fvAccess"
}

userIsAdmin(){
	local userToCheck="$1"
	if [[ $("/usr/sbin/dseditgroup" -o checkmember -m "$userToCheck" admin / 2>&1) =~ "yes" ]]; then
		local admin="true"
	else
		local admin="false"
	fi
	echo "$admin"
}

secureTokenUserCheck() {
	local userToCheck="$1"
	if [[ $("/usr/sbin/sysadminctl" -secureTokenStatus "$userToCheck" 2>&1) =~ "ENABLED" ]]; then
		userToken="true"
	else
		userToken="false"
	fi
	echo "$userToken"
}

addSecureToken() {
	local tokenUser="$1"
	local tokenUserPass="$2"
	local addUser="$3"
	local addUserPass="$4"
	echo "adding token to $addUser with credentials from $tokenUser"
	sysadminctl -adminUser "$tokenUser" -adminPassword "$tokenUserPass" -secureTokenOn "$addUser" -password "$addUserPass"
	tokenAdded=$(secureTokenUserCheck "$addUser")
	echo "Token Added to $addUser : $tokenAdded"
	diskutil apfs listcryptousers /
}

setEAStatus() {

	echo "setting EA status"

	apiData="<computer><extension_attributes><extension_attribute><name>RescuePassword</name><type>String</type><input_type><type>Text Field</type></input_type><value>${rescuePass}</value></extension_attribute></extension_attributes></computer>"
	echo "${apiData}"

	fullURL="$jssURL/JSSResource/computers/udid/$udid/subset/extension_attributes"
	echo "${fullURL}"

	apiPost=$(curl -s -f -u "$apiUser":"$apiPass" -X "PUT" "${fullURL}" -H "Content-Type: application/xml" -H "Accept: application/xml" -d "${apiData}" 2>&1 )

	/bin/echo "${apiPost}"

}

uploadCheck() {
	echo "Checking Password"
	checkPass=$(curl -s -f -u "$apiUser":"$apiPass" -H "Accept: application/xml" $jssURL/JSSResource/computers/udid/"$udid"/subset/extension_attributes | xpath "//extension_attribute[name=$extAttName]" 2>&1 | awk -F'<value>|</value>' '{print $2}')
	checkPass=$(echo "$checkPass" | tr -d '\040\011\012\015')
	echo "$checkPass"
	echo "rescuePass"
	echo "$rescuePass"

	if [[ "$checkPass" == "$rescuePass" ]] ; then
		echo "password uploaded successfully"
		rm -f "$passLocation"
	else
		echo "password failed to upload to jamf"
		echo "trying again"
		setEAStatus
	fi
}

addUserToFilevault() {
	fvUser="${1}"
	fvPass="${2}"
	addUser="${3}"
	addPass="${4}"
	remove="${5:-false}"
	if [[ "$remove" == "true" ]] ; then
		fdesetup remove -user "$addUser"
	fi
#create the plist file:
echo '<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Username</key>
<string>'$fvUser'</string>
<key>Password</key>
<string>'$fvPass'</string>
<key>AdditionalUsers</key>
<array>
	<dict>
		<key>Username</key>
		<string>'$addUser'</string>
		<key>Password</key>
		<string>'$addPass'</string>
	</dict>
</array>
</dict>
</plist>' > /tmp/fvenable.plist  ### you can place this file anywhere just adjust the fdesetup line below

	# now enable FileVault
	fdesetup add -i < /tmp/fvenable.plist

	rm -r /tmp/fvenable.plist
}


#############################################
#############################################
##DO THE THINGS
#############################################
#############################################

rescueExists=$(userExists "$rescueUser" )
rescueIsAdmin=$(userIsAdmin "$rescueUser" )
rescuePassCorrect=$(passwordCorrect "$rescueUser" "$rescuePass")
rescueFV=$(fileVaultUserAccess "$rescueUser" )
rescueToken=$(secureTokenUserCheck "$rescueUser" )

echo " "
echo "Rescue account checks:"
echo "exists: $rescueExists"
echo "admin: $rescueIsAdmin (we want this to be false)"
echo "passCorrect: $rescuePassCorrect"
echo "filevault: $rescueFV"
echo "secureToken: $rescueToken"
echo " "
echo " "

## FIX rescue NOT EXIST
if [[ "$rescueExists" == "false" ]] ; then
	echo "$rescueUser does not exist. Creating account"
	sysadminctl -addUser "$rescueUser" -fullName "$rescueUser" -password "$rescuePass" -adminUser "$adminName" -adminPassword "$adminPass"
	echo "adding $rescueUser icon"
	jamf recon
	sleep 1
	jamf policy -trigger "${rescueUser}icon"

	# update other checks
	rescueExists=$(userExists "$rescueUser" )
	rescueIsAdmin=$(userIsAdmin "$rescueUser" )
	rescuePassCorrect=$(passwordCorrect "$rescueUser" "$rescuePass")
	rescueFV=$(fileVaultUserAccess "$rescueUser" )
	rescueToken=$(secureTokenUserCheck "$rescueUser" )
	if [[ "$rescueExists" == "false" ]] ; then 
		echo "$rescueUser failed to create"
		exit 1
	fi
fi

## FIX rescue IS ADMIN
if [[ "$rescueIsAdmin" == "true" ]] ; then
	echo "$rescueUser is an admin. Demoting account"
	/usr/sbin/dseditgroup -o edit -n /Local/Default -d "$rescueUser" -t "user" "admin"
	sleep 1
	rescueIsAdmin=$(userIsAdmin "$rescueUser" )
	rescuePassCorrect=$(passwordCorrect "$rescueUser" "$rescuePass")
	rescueFV=$(fileVaultUserAccess "$rescueUser" )
	rescueToken=$(secureTokenUserCheck "$rescueUser" )
	if [[ "$rescueIsAdmin" == "true" ]] ; then 
		echo "$rescueUser failed to demote"
		exit 1
	fi
fi

## FIX rescue INCORRECT PASSWORD
if [[ "$rescuePassCorrect" == "false" ]] ; then
	echo "$rescueUser password is incorrect. changing password"
	/usr/sbin/sysadminctl -adminUser "$adminName" -adminPassword "$adminPass" -resetPasswordFor "$rescueUser" -newPassword "$rescuePass"
	sleep 1
	rescuePassCorrect=$(passwordCorrect "$rescueUser" "$rescuePass")
	rescueFV=$(fileVaultUserAccess "$rescueUser" )
	rescueToken=$(secureTokenUserCheck "$rescueUser" )
	if [[ "$rescuePassCorrect" == "false" ]] ; then 
		echo "$rescueUser failed to update password"
		exit 1
	fi
fi

if [[ "$rescueFV" == "false" ]] ; then
	echo "$rescueUser failed FV access"
	addUserToFilevault "$adminName" "$adminPass" "$rescueUser" "$rescuePass"
	sleep 1
	rescueFV=$(fileVaultUserAccess "$rescueUser" )
	rescueToken=$(secureTokenUserCheck "$rescueUser" )
	if [[ "$rescueFV" == "false" ]] ; then 
		echo "$rescueUser failed to update filevault"
		exit 1
	fi
fi

if [[ "$rescueToken" == false ]] ; then
	echo "$rescueUser missing secure token, adding"
	addSecureToken "$adminName" "$adminPass" "$rescueUser" "$rescuePass"
	sleep 1
	rescueToken=$(secureTokenUserCheck "$rescueUser" )
	if [[ "$rescueToken" == "false" ]] ; then 
		echo "$rescueUser failed to update secure token"
		exit 1
	fi
fi

echo " "
echo "Final Checks:"
echo "exists: $rescueExists"
echo "admin: $rescueIsAdmin (we want this to be false)"
echo "passCorrect: $rescuePassCorrect"
echo "filevault: $rescueFV"
echo "secureToken: $rescueToken"
echo " "
echo " "

setEAStatus
uploadCheck

echo " "
echo "Updating apfs preboot"
diskutil apfs updatePreboot / >> /dev/null 2>&1 
